version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
  post_build:
    commands:
      - echo Removing unnecessary files...
      - rm -rf node_modules/
artifacts:
  base-directory: '.'
  files:
    - '**/*'
