version: '3.5'
services:
  postgres:
    image: postgres:12.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  start_dependencies:
    image: dadarek/wait-for-dependencies
    command: postgres:5432
    depends_on:
      - postgres
